<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "em_sys_note"
 *
 * Auto generated by Extension Builder 2019-11-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'sys_note on steroids',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Andreas Kießling',
    'author_email' => 'kiessling@extrameile-gehen.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
